version: '3.7'
services:
  db:
    image: postgres:16.1
    restart: always
    volumes:
      - ./storage/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432

  nats-streaming-server:
    image: nats-streaming:0.25.6
    restart: always
    ports:
      - ${NATS_PORT}:4222
